name: Build Arch ISO
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build In Docker
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        useradd builduser -m
        passwd -d builduser
        pacman -Syu --noconfirm --needed sudo base-devel
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser ./
        ./prepare.sh
        ./build.sh
        EOF

        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
    
    - name: Upload Built ISO
      uses: actions/upload-artifact@v2
      with:
        name: built-iso
        path: ${{ github.workspace }}/out/archlinux*.iso
